// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniEFCoreWithSqliteTest.Database;

#nullable disable

namespace MiniEFCoreWithSqliteTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111014208_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MiniEFCoreWithSqliteTest.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PublicationYearUtcTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1L,
                            AuthorName = "authorName1",
                            BookName = "bookName1",
                            PublicationYearUtcTick = 638984221279990968L,
                            Publisher = "publisher1"
                        },
                        new
                        {
                            BookId = 2L,
                            AuthorName = "authorName2",
                            BookName = "bookName2",
                            PublicationYearUtcTick = 638984221279991175L,
                            Publisher = "publisher2"
                        },
                        new
                        {
                            BookId = 3L,
                            AuthorName = "authorName3",
                            BookName = "bookName3",
                            PublicationYearUtcTick = 638984221279991177L,
                            Publisher = "publisher3"
                        },
                        new
                        {
                            BookId = 4L,
                            AuthorName = "authorName4",
                            BookName = "bookName4",
                            PublicationYearUtcTick = 638984221279991178L,
                            Publisher = "publisher4"
                        },
                        new
                        {
                            BookId = 5L,
                            AuthorName = "authorName5",
                            BookName = "bookName5",
                            PublicationYearUtcTick = 638984221279991179L,
                            Publisher = "publisher5"
                        },
                        new
                        {
                            BookId = 6L,
                            AuthorName = "authorName6",
                            BookName = "bookName6",
                            PublicationYearUtcTick = 638984221279991180L,
                            Publisher = "publisher6"
                        },
                        new
                        {
                            BookId = 7L,
                            AuthorName = "authorName7",
                            BookName = "bookName7",
                            PublicationYearUtcTick = 638984221279991181L,
                            Publisher = "publisher7"
                        },
                        new
                        {
                            BookId = 8L,
                            AuthorName = "authorName8",
                            BookName = "bookName8",
                            PublicationYearUtcTick = 638984221279991182L,
                            Publisher = "publisher8"
                        },
                        new
                        {
                            BookId = 9L,
                            AuthorName = "authorName9",
                            BookName = "bookName9",
                            PublicationYearUtcTick = 638984221279991183L,
                            Publisher = "publisher9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
